{
 "title": "Deliverable 8 Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "live_usage", "legendFormat": "{{method}}" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "live_percentage", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Authentications/minute",
   "type": "timeseries",
   "description": "Keeps track of the number of successful and failed authentication attempts per minute",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(auth_attempt{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "description": "Shows current number of people logged in\n(Logins minus logouts)",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 9 },
   "targets": [
    { "expr": "current_users", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "ongoing_latency{method=\"pizza\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " rate(total_pizzas{method=\"sold\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "total_pizzas{method=\"failed\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " rate(total_revenue[1m])", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "ongoing_latency{method=\"service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}